import { defineConfig, type Plugin } from "vite";
import { cloudflare } from "@cloudflare/vite-plugin";
import swc from "unplugin-swc";
import tailwindcss from "@tailwindcss/postcss";
import autoprefixer from "autoprefixer";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Plugin to generate asset manifest as TypeScript module
 */
function generateAssetManifest(): Plugin {
  let isDev = false;

  return {
    name: "generate-asset-manifest",

    configResolved(config) {
      isDev = config.command === "serve";

      if (isDev) {
        const devContent = `// Auto-generated by Vite - do not edit (dev mode)
export const ASSETS = {
  styles: "/node_modules/@jant/core/src/theme/styles/main.css",
  client: "/node_modules/@jant/core/src/client.ts",
  datastar: "/node_modules/@jant/core/static/assets/datastar.min.js",
} as const;
`;
        // Write to @jant/core's location (will be resolved via workspace)
        const outputPath = resolve(__dirname, "node_modules/@jant/core/src/lib/assets.gen.ts");
        try {
          writeFileSync(outputPath, devContent, "utf-8");
        } catch {
          // Ignore if can't write (not installed yet)
        }
      }
    },

    writeBundle(options, bundle) {
      if (isDev) return;

      const manifestFile = bundle[".vite/manifest.json"];
      if (!manifestFile || manifestFile.type !== "asset") return;

      try {
        const manifest = JSON.parse(manifestFile.source as string);
        const stylesEntry = manifest["src/theme/styles/main.css"];
        const stylesPath = stylesEntry ? `/${stylesEntry.file}` : "/assets/styles.css";
        const clientEntry = manifest["src/client.ts"];
        const clientPath = clientEntry ? `/${clientEntry.file}` : "/client.js";

        const content = `// Auto-generated by Vite - do not edit
export const ASSETS = {
  styles: "${stylesPath}",
  client: "${clientPath}",
  datastar: "/assets/datastar.min.js",
} as const;
`;
        const outputPath = resolve(__dirname, "node_modules/@jant/core/src/lib/assets.gen.ts");
        writeFileSync(outputPath, content, "utf-8");
      } catch {
        // Ignore errors
      }
    },
  };
}

export default defineConfig({
  publicDir: false,
  server: {
    port: 9019,
    host: true,
    allowedHosts: true,
  },
  preview: {
    port: 9019,
  },
  plugins: [
    generateAssetManifest(),
    swc.vite({
      jsc: {
        parser: {
          syntax: "typescript",
          tsx: true,
        },
        transform: {
          react: {
            runtime: "automatic",
            importSource: "hono/jsx",
          },
        },
        target: "es2022",
        experimental: {
          plugins: [
            [
              "@lingui/swc-plugin",
              {
                runtimeConfigModule: {
                  useLingui: ["@jant/core/src/i18n/index.ts", "useLingui"],
                  Trans: ["@jant/core/src/i18n/index.ts", "Trans"],
                },
              },
            ],
          ],
        },
      },
      module: {
        type: "es6",
      },
    }),
    cloudflare({
      configPath: "./wrangler.toml",
    }),
  ],
  css: {
    postcss: {
      plugins: [tailwindcss, autoprefixer],
    },
  },
  build: {
    target: "esnext",
    minify: false,
    manifest: true,
    rollupOptions: {
      external: ["cloudflare:*", "__STATIC_CONTENT_MANIFEST"],
    },
  },
  resolve: {
    alias: {
      "@": "/src",
    },
  },
});
