# Deploy to Cloudflare Workers
# Documentation: https://jant.me/docs/deployment
#
# Required secrets (set in GitHub repo settings):
#   - CF_API_TOKEN: Cloudflare API token with Workers/D1/R2 permissions
#   - CF_ACCOUNT_ID: Your Cloudflare account ID
#   - AUTH_SECRET: Random 32+ character string for authentication

name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: nicepkg/jant/.github/workflows/deploy.yml@v1
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
