/**
 * i18n Module
 */

// Core i18n runtime
export {
  i18n,
  t,
  getLocale,
  setLocale,
  locales,
  baseLocale,
  isLocale,
  type Locale,
  type TranslateOptions,
  type RichTranslateOptions,
} from "./i18n.js";

// Language detection utilities
export {
  detectLanguage,
  isValidLanguage,
  parseAcceptLanguage,
  getLanguageDisplayName,
  getSupportedLanguages,
  LANGUAGE_COOKIE_NAME,
} from "./detect.js";

// Hono middleware
export { i18nMiddleware } from "./middleware.js";

// Load compiled catalogs
import { i18n, type Locale } from "./i18n.js";

// Dynamic import for catalogs (will be generated by lingui compile)
export async function loadCatalogs(): Promise<void> {
  try {
    const [messagesEn, messagesZhHans, messagesZhHant] = await Promise.all([
      import("./locales/en.js").then((m) => m.messages).catch(() => ({})),
      import("./locales/zh-Hans.js").then((m) => m.messages).catch(() => ({})),
      import("./locales/zh-Hant.js").then((m) => m.messages).catch(() => ({})),
    ]);

    // Load all catalogs with English as fallback
    i18n.load("en", messagesEn);
    i18n.load("zh-Hans", { ...messagesEn, ...messagesZhHans });
    i18n.load("zh-Hant", { ...messagesEn, ...messagesZhHant });

    // Activate default locale
    i18n.activate("en");
  } catch {
    // Catalogs not yet compiled, use empty
    i18n.load("en", {});
    i18n.load("zh-Hans", {});
    i18n.load("zh-Hant", {});
    i18n.activate("en");
  }
}
