import { defineConfig, type Plugin } from "vite";
import { cloudflare } from "@cloudflare/vite-plugin";
import swc from "unplugin-swc";
import tailwindcss from "@tailwindcss/postcss";
import autoprefixer from "autoprefixer";
import { writeFileSync, readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Plugin to generate asset manifest as TypeScript module
 * This allows SSR code to import hashed asset paths at build time
 */
function generateAssetManifest(): Plugin {
  let isDev = false;

  return {
    name: "generate-asset-manifest",

    configResolved(config) {
      isDev = config.command === "serve";

      // Generate development fallback immediately when starting dev server
      if (isDev) {
        const devContent = `// Auto-generated by Vite - do not edit (dev mode)
export const ASSETS = {
  styles: "/src/theme/styles/main.css",
  datastar: "/assets/datastar.min.js",
} as const;
`;
        const outputPath = resolve(__dirname, "src/lib/assets.gen.ts");
        writeFileSync(outputPath, devContent, "utf-8");
        console.log("✓ Generated dev asset manifest:", outputPath);
      }
    },

    writeBundle(options, bundle) {
      // Only run in production build
      if (isDev) return;

      // Extract manifest from bundle
      const manifestFile = bundle[".vite/manifest.json"];
      if (!manifestFile || manifestFile.type !== "asset") {
        console.warn("Manifest file not found in bundle");
        return;
      }

      try {
        const manifest = JSON.parse(manifestFile.source as string);

        // Extract CSS path
        const stylesEntry = manifest["src/theme/styles/main.css"];
        const stylesPath = stylesEntry ? `/${stylesEntry.file}` : "/assets/styles.css";

        // Generate TypeScript module
        const content = `// Auto-generated by Vite - do not edit
export const ASSETS = {
  styles: "${stylesPath}",
  datastar: "/assets/datastar.min.js",
} as const;
`;

        // Write to src/lib/assets.gen.ts
        const outputPath = resolve(__dirname, "src/lib/assets.gen.ts");
        writeFileSync(outputPath, content, "utf-8");
        console.log("✓ Generated asset manifest:", outputPath);
      } catch (error) {
        console.warn("Failed to generate asset manifest:", error);
      }
    },
  };
}

export default defineConfig({
  publicDir: "static", // Copy static files to output
  server: {
    host: true, // Listen on all addresses (0.0.0.0) for local network access
    port: 9019,
    allowedHosts: [
      "local.jant.me",
      ".local.jant.me", // Allow subdomains
    ],
  },
  preview: {
    host: true,
    port: 9019,
  },
  plugins: [
    // Generate asset manifest for SSR
    generateAssetManifest(),
    // SWC plugin for Hono JSX and Lingui macros
    swc.vite({
      jsc: {
        parser: {
          syntax: "typescript",
          tsx: true,
        },
        transform: {
          react: {
            runtime: "automatic",
            importSource: "hono/jsx",
          },
        },
        target: "es2022",
        experimental: {
          plugins: [
            [
              "@lingui/swc-plugin",
              {
                // Lingui macro transformation
              },
            ],
          ],
        },
      },
      module: {
        type: "es6",
      },
    }),
    // Cloudflare Workers integration
    cloudflare({
      configPath: "./wrangler.toml",
    }),
  ],
  css: {
    postcss: {
      plugins: [tailwindcss, autoprefixer],
    },
  },
  build: {
    target: "esnext",
    minify: false, // Wrangler will handle minification
    manifest: true, // Generate manifest.json for asset mapping
    rollupOptions: {
      input: {
        main: "./src/index.ts",
        styles: "./src/theme/styles/main.css",
      },
      output: {
        entryFileNames: "[name]-[hash].js",
        chunkFileNames: "[name]-[hash].js",
        assetFileNames: "assets/[name]-[hash][extname]",
      },
      external: ["cloudflare:*", "__STATIC_CONTENT_MANIFEST"],
    },
  },
  resolve: {
    alias: {
      "@": "/src",
    },
  },
});
