/**
 * Sqids - Short unique IDs for URLs
 *
 * Encodes numeric IDs to short strings like "jR3k"
 */

import Sqids from "sqids";

const sqids = new Sqids({
  minLength: 4,
});

/**
 * Encodes a numeric database ID to a short, URL-friendly string.
 *
 * Uses the Sqids library to generate short unique identifiers with a minimum length of 4 characters.
 * These are used in URLs (e.g., `/p/jR3k`) to obscure sequential integer IDs while maintaining
 * uniqueness and reversibility.
 *
 * @param id - The numeric database ID to encode
 * @returns A short string representation of the ID (minimum 4 characters)
 *
 * @example
 * ```ts
 * const sqid = encode(123);
 * // Returns: "jR3k" (or similar short string)
 * ```
 */
export function encode(id: number): string {
  return sqids.encode([id]);
}

/**
 * Decodes a sqid string back to the original numeric database ID.
 *
 * Attempts to decode a sqid string generated by the `encode()` function. Returns the original
 * numeric ID if valid, or `null` if the string is not a valid sqid. This is used to extract
 * database IDs from URL parameters.
 *
 * @param str - The sqid string to decode
 * @returns The original numeric ID if valid, or `null` if decoding fails
 *
 * @example
 * ```ts
 * const id = decode("jR3k");
 * // Returns: 123
 *
 * const invalid = decode("invalid");
 * // Returns: null
 * ```
 */
export function decode(str: string): number | null {
  try {
    const ids = sqids.decode(str);
    return ids[0] ?? null;
  } catch {
    return null;
  }
}

/**
 * Checks if a string is a valid sqid that can be decoded.
 *
 * Validates whether a string can be successfully decoded to a numeric ID.
 * Useful for route validation and input sanitization.
 *
 * @param str - The string to validate
 * @returns `true` if the string is a valid sqid, `false` otherwise
 *
 * @example
 * ```ts
 * if (isValidSqid("jR3k")) {
 *   // Process the valid sqid
 * }
 * ```
 */
export function isValidSqid(str: string): boolean {
  return decode(str) !== null;
}
